#!/usr/bin/env python3
"""Populate emoji column on N5-Vocab.csv from EXACT + category fallbacks."""
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "src" / "N5-Vocab.csv"

EXACT = {
    "hello, good afternoon": "👋",
    "good morning (polite)": "🌅",
    "good morning (casual)": "☀️",
    "good evening": "🌆",
    "good night (polite)": "🌙",
    "good night (casual)": "😴",
    "goodbye (formal)": "🎩",
    "bye (casual)": "✌️",
    "thank you (polite)": "🙏",
    "thank you (casual)": "💐",
    "excuse me, i'm sorry": "🔔",
    "i'm sorry": "😔",
    "you're welcome": "😊",
    "nice to meet you": "🤝",
    "please treat me well": "🌸",
    "how are you?": "💬",
    "i'm fine": "😄",
    "let's eat (before meal)": "🍽️",
    "thank you for the meal": "🍱",
    "i'm heading out": "🚶",
    "have a good trip (response)": "✈️",
    "i'm home": "🏠",
    "welcome back": "🏡",
    "thanks": "😌",
    "please": "🙌",
    "yes": "✅",
    "no": "❌",
    "not very": "😐",
    "(humble) i,myself": "🙇",
    "i,myself": "🧍",
    "how": "🤔",
    "how many?,how old?": "🔢",
    "how much?": "💰",
    "how,in what way": "❓",
    "however": "↔️",
    "for what reason": "🔍",
    "what": "❔",
    "where": "📍",
    "when": "⏰",
    "who": "👤",
    "why": "🤷",
    "more": "➕",
    "very": "‼️",
    "together": "🤗",
    "again,and": "🔄",
    "and": "＆",
    "but": "🔀",
    "in that situation": "💡",
    "sometimes": "🕐",
    "that": "👉",
    "this": "👈",
    "this person or way": "🧭",
    "this year": "📅",
    "one": "1️⃣",
    "one person": "🧑",
    "to take time or money": "⌛",
    "two": "2️⃣",
    "two people": "👫",
    "which of two": "⚖️",
    "three": "3️⃣",
    "which (of three or more)": "🔀",
    "four": "4️⃣",
    "five": "5️⃣",
    "six": "6️⃣",
    "seven": "7️⃣",
    "eight": "8️⃣",
    "nine": "9️⃣",
    "ten": "🔟",
    "ten thousand": "💫",
    "hundred": "💯",
    "thousand": "🔢",
    "half": "½",
    "half minute": "⏱️",
    "for the first time": "🌟",
    "time": "⏰",
    "20 years old,20th year": "🎊",
    "best, first": "🥇",
    "gram": "⚖️",
    "great number of people": "👥",
    "kilogram": "🏋️",
    "metre": "📏",
    "number": "#️⃣",
    "monday": "📅",
    "tuesday": "📆",
    "wednesday": "📇",
    "thursday": "🗓️",
    "friday": "🎉",
    "saturday": "🏖️",
    "sunday": "⛪",
    "today": "🗒️",
    "tomorrow": "🌄",
    "yesterday": "↩️",
    "day": "☀️",
    "week": "📅",
    "every day": "🔁",
    "weekend": "🎊",
    "holiday": "🎌",
    "january": "❄️",
    "february": "💝",
    "march": "🌸",
    "april": "🌼",
    "may": "🌿",
    "june": "☔",
    "july": "🎆",
    "august": "🌊",
    "september": "🍂",
    "october": "🎃",
    "november": "🍁",
    "december": "🎄",
    "month": "🗓️",
    "year": "📅",
    "spring": "🌸",
    "summer": "☀️",
    "autumn": "🍂",
    "fall": "🍂",
    "winter": "❄️",
    "sunny": "☀️",
    "cloudy": "☁️",
    "rainy": "🌧️",
    "rainy season": "🌂",
    "rain": "🌧️",
    "snow": "🌨️",
    "wind": "💨",
    "hot": "🌡️",
    "cold": "🥶",
    "weather": "🌤️",
    "temperature": "🌡️",
    "typhoon": "🌀",
    "fine weather": "🌤️",
    "fog": "🌫️",
    "warm": "🌞",
    "cool": "🌬️",
    "storm": "⛈️",
    "thunder": "⚡",
    "(honorable) father": "👨",
    "grandfather, male senior citizen": "👴",
    "(honorable) mother": "👩",
    "grandmother, female senior-citizen": "👵",
    "both parents": "👨‍👩‍👧",
    "(honorable) older brother": "👦",
    "(humble) older brother": "🧑",
    "(honorable) older sister": "👧",
    "(humble) older sister": "🧒",
    "younger brother": "👦‍🦱",
    "(humble) younger sister": "👶",
    "child": "🧸",
    "adult": "🧑",
    "man": "🧔",
    "woman": "👱‍♀️",
    "friend": "🤝",
    "(honorable) wife": "👰",
    "boy": "👦",
    "family": "👨‍👩‍👧‍👦",
    "girl": "👧",
    "head": "🗣️",
    "eye": "👁️",
    "ear": "👂",
    "nose": "👃",
    "mouth, opening": "👄",
    "tooth": "🦷",
    "hand": "✋",
    "left hand side": "👈",
    "to hand over": "🤲",
    "to go back": "🔙",
    "foot, leg": "🦶",
    "voice": "🎙️",
    "body": "🧍",
    "to brush teeth, to polish": "🪥",
    "red": "🔴",
    "blue": "🔵",
    "yellow": "🟡",
    "green": "🟢",
    "white": "⬜",
    "black": "⬛",
    "brown": "🟤",
    "colour": "🎨",
    "water": "💧",
    "a drink": "🥤",
    "black tea": "🫖",
    "green tea": "🍵",
    "coffee": "☕",
    "milk": "🥛",
    "alcohol, rice wine": "🍶",
    "cooked rice, meal": "🍚",
    "rice bowl": "🍜",
    "bread": "🍞",
    "egg": "🥚",
    "candy": "🍬",
    "sweets, candy": "🍭",
    "breakfast": "🥞",
    "midday meal": "🥡",
    "dinner": "🍽️",
    "evening meal": "🌙",
    "boxed lunch": "🍱",
    "delicious": "😋",
    "dining hall": "🏫",
    "food": "🍲",
    "spicy": "🌶️",
    "to drink": "🥤",
    "business shirt": "👔",
    "shirt": "👕",
    "jacket": "🧥",
    "coat, tennis court": "🎾",
    "sweater, jumper": "🧶",
    "to wear,to put on trousers": "👖",
    "trousers": "👖",
    "hat": "🎩",
    "shoes": "👟",
    "socks": "🧦",
    "slippers": "🩴",
    "glasses": "👓",
    "clothes": "👗",
    "tie,necktie": "👔",
    "to take off clothes": "🧹",
    "to tie": "🪢",
    "western-style clothes": "🤵",
    "house": "🏠",
    "room": "🛋️",
    "japanese style door": "🚪",
    "next door to": "🏘️",
    "western style door": "🚪",
    "window": "🪟",
    "kitchen": "🍳",
    "toilet": "🚽",
    "garden": "🌻",
    "table": "🪑",
    "bed": "🛏️",
    "to go to bed,to sleep": "😴",
    "television": "📺",
    "tape recorder": "📼",
    "knife": "🔪",
    "fork": "🍴",
    "spoon": "🥄",
    "cup": "☕",
    "ashtray": "🚭",
    "key": "🔑",
    "bath": "🛁",
    "box": "📦",
    "camera": "📷",
    "elevator": "🛗",
    "envelope": "✉️",
    "heater": "🔥",
    "refrigerator": "🧊",
    "stairs": "🪜",
    "tape": "📼",
    "watch,clock": "⌚",
    "dog": "🐕",
    "cat": "🐈",
    "bird": "🐦",
    "fish": "🐟",
    "animal": "🐾",
    "animal noise. to chirp, roar or croak etc.": "🔊",
    "north": "⬆️",
    "south": "⬇️",
    "east": "➡️",
    "west": "⬅️",
    "right side": "👉",
    "here": "📌",
    "over there": "👆",
    "that over there": "☝️",
    "there": "🗺️",
    "outside": "🌳",
    "near, beside": "📍",
    "school": "🏫",
    "hospital": "🏥",
    "bank": "🏦",
    "post office": "📮",
    "shop": "🏪",
    "department store": "🏬",
    "restaurant": "🍴",
    "park": "🌳",
    "station": "🚉",
    "hotel": "🏨",
    "street": "🛣️",
    "gate": "⛩️",
    "bridge": "🌉",
    "town,city": "🌆",
    "country": "🌏",
    "foreign country": "🌐",
    "afterwards": "⏭️",
    "place": "📍",
    "that place": "🗺️",
    "after that": "⏩",
    "before": "⏮️",
    "beside,side,width": "↔️",
    "chopsticks": "🥢",
    "cinema": "🎬",
    "coffee lounge": "☕",
    "embassy": "🏛️",
    "entrance": "🚪",
    "entry hall": "🏠",
    "exit": "🚶",
    "intersection": "🛤️",
    "library": "📚",
    "map": "🗺️",
    "middle": "🎯",
    "next": "▶️",
    "next year": "📆",
    "pond": "🐸",
    "uncle, middle aged gentleman": "🧓",
    "village": "🏡",
    "year after next": "🔮",
    "year before last": "📇",
    "car, vehicle": "🚗",
    "automobile": "🚘",
    "bus": "🚌",
    "taxi": "🚕",
    "bicycle": "🚲",
    "electric train": "🚆",
    "underground train": "🚇",
    "ticket": "🎫",
    "aeroplane": "✈️",
    "medical doctor": "👨‍⚕️",
    "company": "🏢",
    "job": "💼",
    "lesson, class work": "📖",
    "to work": "⚙️",
    "to work for someone": "👷",
    "foreigner": "🌏",
    "police box": "🚔",
    "music": "🎵",
    "movie": "🎬",
    "photograph": "📸",
    "party": "🎉",
    "travel": "✈️",
    "swimming pool": "🏊",
    "sport": "🏅",
    "guitar": "🎸",
    "to play an instrument with strings, including piano": "🎹",
    "big": "🐘",
    "little": "🐭",
    "tall, expensive": "💎",
    "short": "📐",
    "short,low": "🪨",
    "long": "📏",
    "narrow": "↕️",
    "spacious,wide": "↔️",
    "heavy": "🏋️",
    "light": "🪶",
    "late, slow": "🐢",
    "near": "🔍",
    "far": "🔭",
    "new": "✨",
    "household": "🏠",
    "old (not used for people)": "🏚️",
    "young": "🌱",
    "good": "⭐",
    "bad": "💔",
    "luke warm": "🌡️",
    "easy, simple": "😊",
    "difficult": "🧩",
    "difficult situation": "😰",
    "noisy, annoying": "📢",
    "bustling,busy": "🏙️",
    "busy, irritated": "😤",
    "pretty, clean": "💐",
    "dirty": "🗑️",
    "bright": "💡",
    "strong, durable": "💪",
    "thin,weak": "🥀",
    "weak": "🌾",
    "fat": "🍩",
    "thin": "🪶",
    "free time": "🕊️",
    "interesting": "🤩",
    "boring": "😑",
    "same": "🟰",
    "(humble) siblings": "👫",
    "a few": "🤏",
    "bathroom": "🚿",
    "cheap": "🏷️",
    "cute": "🥰",
    "dangerous": "⚠️",
    "early": "⏰",
    "enjoyable": "🎊",
    "famous": "⭐",
    "few": "🤏",
    "gloomy": "🌧️",
    "hate": "👎",
    "homework": "📋",
    "many": "🌊",
    "painful": "🤕",
    "powerful": "⚡",
    "problem": "❗",
    "quick": "⚡",
    "refreshing": "🌬️",
    "round,circular": "⭕",
    "sweet": "🍭",
    "unpleasant": "😖",
    "vegetable": "🥦",
    "want": "🌟",
    "zero": "0️⃣",
    "to be able to": "✅",
    "to be born": "👶",
    "to be understood": "💡",
    "to be very likeable": "😍",
    "to be worried": "😟",
    "to be, to have (used for people and animals)": "🧍",
    "to be,to have (used for inanimate objects)": "📦",
    "to become": "🦋",
    "to begin": "🚀",
    "to close, to be closed": "🔒",
    "to open, to become open": "🔓",
    "to turn,to bend": "↩️",
    "to do": "🔨",
    "to go": "➡️",
    "to go across": "🌉",
    "to go out": "🚶",
    "to come": "⬅️",
    "to come to a halt": "🛑",
    "to return something": "↩️",
    "to enter,to contain": "🚪",
    "to appear,to leave": "👻",
    "to arrive at": "📍",
    "to meet": "🤝",
    "to hear, to listen to, to ask": "👂",
    "to speak": "🗣️",
    "to read": "📖",
    "to write": "✍️",
    "to remember": "🧠",
    "to forget": "🫥",
    "to know": "💡",
    "to see, to watch": "👀",
    "to bathe, to shower": "🚿",
    "to show": "🪄",
    "to eat": "🍽️",
    "to make": "🔧",
    "to play, to make a visit": "🎮",
    "to buy": "🛍️",
    "to sell": "💰",
    "to open": "🔓",
    "to close something": "🔒",
    "to put": "📦",
    "to put in": "📥",
    "to put on from the shoulders down": "🧥",
    "to put out": "📤",
    "to take a photo or record a film": "📷",
    "to take something": "✋",
    "to give": "🎁",
    "to borrow": "🤲",
    "to lend": "🫱",
    "to wash": "🧼",
    "to clean, to sweep": "🧹",
    "to practice": "🏋️",
    "to teach, to tell": "🎓",
    "to learn": "📚",
    "to sit": "🪑",
    "to line up,to stand in a line": "🚶",
    "to stand": "🧍",
    "to rest": "😴",
    "to walk": "🚶",
    "to run": "🏃",
    "to swim": "🏊",
    "to call by phone": "📞",
    "to call out,to invite": "📣",
    "to finish": "✅",
    "to pull": "🔙",
    "to push, to stamp something": "🤜",
    "to turn on": "💡",
    "to erase, to turn off power": "🔦",
    "to use": "🔧",
    "to wait": "⏳",
    "to need": "📌",
    "all": "🌐",
    "all right": "👍",
    "already": "✔️",
    "beef": "🥩",
    "chair": "🪑",
    "chicken meat": "🍗",
    "classroom": "🏫",
    "important": "❗",
    "luggage": "🧳",
    "meat": "🥩",
    "noon, daytime": "🌞",
    "often, well": "🔁",
    "pork": "🐖",
    "sentence,text": "📝",
    "splendid, enough": "🌟",
    "straight ahead,direct": "⬆️",
    "sugar": "🍬",
    "to ask": "🙋",
    "to bloom": "🌸",
    "to blow": "💨",
    "to climb": "🧗",
    "to copy": "📋",
    "to cut": "✂️",
    "to die": "💀",
    "to differ": "🔀",
    "to disappear": "🌫️",
    "to fly,to hop": "🕊️",
    "to get off, to descend": "⬇️",
    "to get on,to ride": "🚌",
    "to get tired": "😓",
    "to get up": "⏰",
    "to hold": "🫳",
    "to line up,to set up": "📐",
    "to live in": "🏡",
    "to lose something": "🔍",
    "to say": "🗣️",
    "to sing": "🎤",
    "to smoke, to suck": "🚬",
    "to stick": "📌",
    "to stretch out hands, to raise an umbrella": "☂️",
    "to stroll": "🌸",
    "truth": "📖",
    "used for comparison.": "⚖️",
    "washing": "🫧",
    "person": "🧑",
    "person, way of doing": "🧭",
    "somebody": "👤",
    "everyone": "👥",
    "thing": "📦",
    "word, language": "🗣️",
    "meaning": "💬",
    "english language": "🇬🇧",
    "question": "❓",
    "to answer": "💬",
    "test": "📝",
    "book": "📕",
    "bookshelves": "📚",
    "notebook,exercise book": "📓",
    "dictionary": "📖",
    "ball-point pen": "🖊️",
    "fountain pen": "🖋️",
    "pen": "✒️",
    "pencil": "✏️",
    "overseas student": "🎒",
    "student": "🧑‍🎓",
    "teacher, doctor": "👨‍🏫",
    "class": "🏫",
    "composition, writing": "📝",
    "talk,story": "💬",
    "letter": "💌",
    "to study": "📖",
    "electricity,electric light": "💡",
    "always": "♾️",
    "which": "🔀",
    "somewhat": "🤏",
    "shower": "🚿",
    "a corner": "📐",
    "a glass": "🥛",
    "a vase": "🏺",
    "again": "🔁",
    "apartment": "🏢",
    "area": "🗺️",
    "aunt": "👩",
    "bag, basket": "👜",
    "beginning": "🚀",
    "behind": "⬅️",
    "below": "⬇️",
    "birthday": "🎂",
    "building": "🏗️",
    "business suit": "🤵",
    "butter": "🧈",
    "button": "🔘",
    "calendar": "📅",
    "chinese character": "漢",
    "corridor": "🚶",
    "cuisine": "🍽️",
    "curry": "🍛",
    "desk": "🖥️",
    "economy": "💹",
    "et cetera": "…",
    "every year": "📆",
    "exactly": "✔️",
    "friendly term for policeman": "👮",
    "fruit": "🍎",
    "gradually": "📈",
    "greengrocer": "🥬",
    "handkerchief": "🧣",
    "health, vitality": "💪",
    "height, stature": "📏",
    "illness": "🤒",
    "instantly": "⚡",
    "kilometer": "🛣️",
    "last year": "📅",
    "length,height": "📐",
    "likeable": "💕",
    "magazine": "📰",
    "marriage": "💍",
    "match": "🏆",
    "medicine": "💊",
    "money": "💵",
    "name": "🏷️",
    "news": "📰",
    "newspaper": "🗞️",
    "now": "⏱️",
    "on top of": "⬆️",
    "oneself": "🪞",
    "other, the rest": "🔖",
    "page": "📄",
    "paper": "📄",
    "pet": "🐾",
    "picture": "🖼️",
    "plate, dish": "🍽️",
    "pocket": "🧥",
    "policeman": "👮",
    "post": "📮",
    "postage stamp": "📮",
    "postcard": "📬",
    "probably": "🤔",
    "pupil": "🎒",
    "quiet": "🤫",
    "radio": "📻",
    "radio cassette player": "📼",
    "record": "💿",
    "rest,holiday": "🏖️",
    "roll of film": "🎞️",
    "salt": "🧂",
    "shopping": "🛒",
    "skillful": "🎯",
    "skirt": "👗",
    "slowly": "🐢",
    "song": "🎶",
    "soy sauce": "🍱",
    "splendid": "🌟",
    "stomach": "🫃",
    "such": "🎭",
    "telephone": "☎️",
    "the future, previous": "🔮",
    "tobacco,cigarettes": "🚬",
    "twenty days,twentieth": "📅",
    "um...": "💭",
    "umbrella": "☂️",
    "university": "🎓",
    "unskillful": "🤦",
    "useful, convenient": "🛠️",
    "various": "🎨",
    "wallet": "👛",
    "well…": "🤷",
    "you": "👉",
}

used = set()

def assign_emoji(english: str, category: str):
    cat = (
        str(category).strip().lower()
        if category is not None and not pd.isna(category)
        else ""
    )
    key = english.lower().strip()
    val = EXACT.get(key)
    if val and val not in used:
        used.add(val)
        return val
    for k, v in EXACT.items():
        if k in key and v not in used:
            used.add(v)
            return v
    for k, v in EXACT.items():
        if key in k and v not in used:
            used.add(v)
            return v
    val = EXACT.get(key)
    if val:
        return val
    for k, v in EXACT.items():
        if k in key:
            return v
    cat_defaults = {
        "greetings": "💬",
        "numbers": "🔢",
        "days": "📅",
        "months": "🗓️",
        "seasons": "🌍",
        "weather": "⛅",
        "family": "👨‍👩‍👧",
        "body": "🦾",
        "colors": "🌈",
        "food": "🥘",
        "clothes": "👚",
        "house": "🏘️",
        "animals": "🦊",
        "places": "🌐",
        "transport": "🚐",
        "jobs": "🔭",
        "hobbies": "🎯",
        "sports": "🏆",
        "instruments": "🎼",
        "adjectives": "💫",
        "verbs": "⚙️",
        "classroom": "🏫",
    }
    return cat_defaults.get(cat, "🔷")


def main():
    csv_path = Path(sys.argv[1]) if len(sys.argv) > 1 else CSV_PATH
    df = pd.read_csv(csv_path, encoding="utf-8")

    cat_col = "Categories"
    if cat_col not in df.columns:
        for c in df.columns:
            if c.strip().lower() == "categories":
                cat_col = c
                break
        else:
            print("Column Categories not found.", file=sys.stderr)
            sys.exit(1)

    if "english" not in df.columns:
        print("Column english not found.", file=sys.stderr)
        sys.exit(1)

    used.clear()
    df["emoji"] = df.apply(
        lambda row: assign_emoji(str(row["english"]), row[cat_col]), axis=1
    )

    out_cols = ["japanese", "english", cat_col, "emoji"]
    df[out_cols].to_csv(csv_path, index=False, encoding="utf-8")

    uniq = df["emoji"].nunique()
    print(f"Wrote {csv_path}")
    print(f"Unique emojis: {uniq} / {len(df)} rows")


if __name__ == "__main__":
    main()
